server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_IP}

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    key: ${NAVER_CLIENT_KEY}
  api:
    baseurl: ${NAVER_SEARCH_URL}