# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Momuckji-backend Build & Test CI

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      REDIS_IP: ${{secrets.REDIS_IP}}
      REDIS_PORT: ${{secrets.REDIS_PORT}}
      NAVER_CLIENT_ID: ${{secrets.NAVER_CLIENT_ID}}
      NAVER_CLIENT_KEY: ${{secrets.NAVER_CLIENT_KEY}}
      NAVER_SEARCH_URL: ${{secrets.NAVER_SEARCH_URL}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew :test
      - name: Build with Gradle
        run: ./gradlew build
